sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  - QA

jobs:
  include:
    - stage: Seneca-Jobqueue-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t seneca_jobqueue_flowz:latest ./JobQue/;
            docker images;
            docker tag seneca_jobqueue_flowz:latest $DOCKER_USERNAME_FLOWZ/seneca_jobqueue_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/seneca_jobqueue_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t seneca_jobqueue_flowz:dev ./JobQue/;
            docker images;
            docker tag seneca_jobqueue_flowz:dev $DOCKER_USERNAME/seneca_jobqueue_flowz:dev;
            docker push $DOCKER_USERNAME/seneca_jobqueue_flowz:dev;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t seneca_jobqueue_flowz:qa ./JobQue/;
            docker images;
            docker tag seneca_jobqueue_flowz:qa $DOCKER_USERNAME/seneca_jobqueue_flowz:qa;
            docker push $DOCKER_USERNAME/seneca_jobqueue_flowz:qa;
        fi'
    - stage: Flowz-Frontend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t mom_frontend_flowz:latest --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" ./client/;
            docker images;
            docker tag mom_frontend_flowz:latest $DOCKER_USERNAME_FLOWZ/mom_frontend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/mom_frontend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t mom_frontend_flowz:dev --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" ./client/;
            docker images;
            docker tag mom_frontend_flowz:dev $DOCKER_USERNAME/mom_frontend_flowz:dev;
            docker push $DOCKER_USERNAME/mom_frontend_flowz:dev;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t mom_frontend_flowz:qa --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="$AWS_SECRETKEY" ./client/;
            docker images;
            docker tag mom_frontend_flowz:qa $DOCKER_USERNAME/mom_frontend_flowz:qa;
            docker push $DOCKER_USERNAME/mom_frontend_flowz:qa;
        fi'
    - stage: Flowz-Backend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t flowz_backend_flowz:latest ./service/;
            docker images;
            docker tag flowz_backend_flowz:latest $DOCKER_USERNAME_FLOWZ/flowz_backend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/flowz_backend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_backend_flowz:dev ./service/;
            docker images;
            docker tag flowz_backend_flowz:dev $DOCKER_USERNAME/flowz_backend_flowz:dev;
            docker push $DOCKER_USERNAME/flowz_backend_flowz:dev;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t flowz_backend_flowz:qa ./service/;
            docker images;
            docker tag flowz_backend_flowz:qa $DOCKER_USERNAME/flowz_backend_flowz:qa;
            docker push $DOCKER_USERNAME/flowz_backend_flowz:qa;
        fi'
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - rbajaniya@officebrain.com
    on_success: always
    on_failure: always
 
 
 
